### ISSUE TITLE
Description of `_atom_type_scat.versus_stol_list`

### ISSUE THREAD

**Issue by rowlesmr** [COMCIFS/cif_core#370] opened 2023-04-09 02:42 UTC
The description of `_atom_type_scat.versus_stol_list` is:
>    List of scattering factors as a function of sin theta on lambda.
    List has the form [[<stol value 1> <scatfac 1>] [<stol value 2> <scatfac
    2>] ....] in increments of 0.01, increasing from 0.0.

Taken strictly, the `<stol value n>` are redundant, as you can calculate the stol value from the position in the list.
Otherwise, the "in increments of 0.01, increasing from 0.0" is not needed.

Suggested definitions:
>    List of scattering factors as a function of sin theta on lambda (stol).
    List has the form [ <scatfac 1>  <scatfac 2> ...] in stol increments of 
    0.01, increasing from 0.0.

Note: this changes the data structure. Is `_atom_type_scat.versus_stol_list` used in the COD?

or

>    List of scattering factors as a function of sin theta on lambda.
    List has the form [[<stol value 1> <scatfac 1>] [<stol value 2> <scatfac
    2>] ....], where the given values of stol allow for the calculation of the
    scattering factors over the range of the refined model.

**Comment by vaitkus** [comment] 2023-04-10 13:25
There are not a lot of entries with in the COD with the `_atom_type_scat.versus_stol_list` item (33 entries out of 500 000, COD revision 282530), but it was already agreed in issue #216 that the definition of this item should be reverted to match the one in the DDL1 dictionary and then potentially deprecated in favour of a separate category. The DDL1 version defined it as a free-form text field and strongly recommended using a formatted list, but other than that did not impose any strict requirements on the items. The new approach that formalises the  table is of course preferable, but the old item should be retained for backwards-compatibility and archival purposes.

That being said, I am unsure if the 0.01 increments should be explicitly provided as a requirement rather than a strong recommendation. For example, COD entry 4001518 which uses the DDL1 version of the  `_atom_type_scat.versus_stol_list` contains lists with the increments of 0.05, i.e.:
```
loop_
_atom_type_symbol
_atom_type_scat_dispersion_real
_atom_type_scat_dispersion_imag
_atom_type_scat_source
_atom_type_scat_versus_stol_list
Pd -0.999 1.007 'International Tables Vol C Tables  4.2.6.8 and 6.1.1.1'
;
 stol     0.00    0.05    0.10    0.15    0.20    0.25    0.30    0.35    0.40  
  f     46.000  45.232  43.172  40.357  37.286  34.283  31.523  29.077  26.961  
 stol     0.45    0.50    0.55    0.60    0.65    0.70    0.75    0.80    0.85  
  f     25.153  23.617  22.307  21.177  20.186  19.296  18.482  17.711  16.979  
 stol     0.90    0.95    1.00    1.05    1.10    1.15    1.20    1.25    1.30  
  f     16.266  15.573  14.893  14.228  13.580  12.950  12.342  11.757  11.200  
 stol     1.35    1.40    1.45    1.50    1.55    1.60    1.65    1.70    1.75  
  f     10.671  10.173   9.705   9.270   8.865   8.492   8.148   7.833   7.545  
;
```

Should we mark this issue as a duplicate of #216 or do you see this discussion going a different way?

**Comment by rowlesmr** [comment] 2023-04-10 14:02
Duplicate of #216 

I'll think on how to include a new category. The s-grid in ITC isn't 0.01 either, so, we've got that going for us...

**Comment by rowlesmr** [comment] 2023-04-10 14:03
Duplicate of https://github.com/COMCIFS/cif_core/issues/216

**Comment by vaitkus** [comment] 2023-06-28 00:52
Closing the issue since it is a duplicate.

**Closed by vaitkus** 2023-06-28 00:52 UTC
Labels: duplicate
